# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-02 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_store',
            field=models.ManyToManyField(to='shop.Store', verbose_name='availability(ies) in store(s)'),
        ),
    ]
